### ISSUE TITLE
Input color using a text box

### ISSUE THREAD

**Issue by Junortiz** [mohad12211/TwitchDownloader-gui#1]
It would be nice to be able to input the individual R, G, B and Alpha values individually. It's true that you can use the hex color value for the the first three but not for the alpha value.

**Comment by mohad12211** [comment]
https://user-images.githubusercontent.com/51754973/197409832-ca1a8f56-41da-40b0-9676-adb41dd851fb.mp4

you can right-click on the slider to specify a percentage of transparency, I think the current configuration is alright, because this is using `gtk_color_button` with no modifications, doing what you've suggested will require to do a custom widget, possible but I don't it's necessary.
